### ISSUE TITLE
clarify select_by_key usage for first column: seqname/chrom

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#100]
select_by_key is not really clear about using first 8 columns of gtf as key. We only have examples with the "feature" one. This could be more explicit, especially because the key for the first column is "chrom" whereas it is called "seqname" in gtf specs.

**Comment by dputhier** [comment]
Yes. We should add example with 'basic features' (first 8) and accept  seqname (seqid and chrom are accepted).

**Comment by dputhier** [comment]
Added some info in CLI and documentation. The select_by_key now accept seqname (and seq_name).
fixed in  a0c82ea070b477fd281d60b1381112811fdb5eba

**Comment by dputhier** [comment]
Thx for reporting.
