### ISSUE TITLE
OLOGRAM : error and mix in chromosome types (string and integer)

### ISSUE THREAD

**Issue by Yghdrazill** [dputhier/pygtftk#106]
Hi, 

I just installed and used a bit gtftk / ologram through conda. The problem i have is that to make it running i need to remove every feature occurring in chromosomes X and Y.

If i don't do it the program stops and give me this error : 

> /homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/cmd_manager.py:954: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
>   fun(**args)
> Traceback (most recent call last):
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/bin/gtftk", line 104, in <module>
>     args = main()
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/bin/gtftk", line 89, in main
>     CmdManager.run(args)
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/cmd_manager.py", line 954, in run
>     fun(**args)
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/plugins/ologram.py", line 628, in ologram
>     hits[feat_type] = overlap_partial(bedA=peak_file, bedB=gtf_sub_bed, ft_type=feat_type)
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/pygtftk/stats/intersect/overlap_stats_shuffling.py", line 194, in compute_overlap_stats
>     Lr2, Li2, all_chrom2 = read_bed.bed_to_lists_of_intervals(bed_B_as_pybedtool, chrom_len)
>   File "pygtftk/stats/intersect/read_bed/read_bed_as_list.pyx", line 66, in pygtftk.stats.intersect.read_bed.read_bed_as_list.bed_to_lists_of_intervals
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 264, in unique
>     ret = _unique1d(ar, return_index, return_inverse, return_counts)
>   File "/homegalio1/eq_jcl/miniconda3/envs/pygtftk/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 312, in _unique1d
>     ar.sort()
> TypeError: '<' not supported between instances of 'str' and 'int'
> 

If i remove the annotations in X and Y chr, program runs and everything is fine. Yet, i would like to be able to run my analyses also on those chromosomes... Any insights ?

Thanks a lot

Léo (from IGMM ;))

**Comment by dputhier** [comment]
Hi Léo (from IGMM :)),
Thanks a lot for your interest in OLOGRAM. Could you elaborate a little bit please. 
- For instance could you provide us with a skeleton of the command line to used to call gtftk. 
- Also, it would be helpful to know about the chromosome that are present or not in the GTF/BED/ChromInfo files so that we can try to recreate the issue. 
- Does the -fwq argument solve the issue ?

This seems to be a basic issue related to str/int comparison (TypeError: '<' not supported between instances of 'str' and 'int').
Best

**Comment by qferre** [comment]
Hi Léo, 
Just a quick question : what is the format of your chromosomes, is there the "chr" at the beginning ?
By which I mean, are they represented as "chr1", "chr2", "chrX", or as "1", "2", "X" ?
Best

**Comment by dputhier** [comment]
@qferre 
OK. I managed to recreate the bug:

     gtftk ologram -i simple.gtf -p simple_peaks.bed -c simple.chromInfo

The modified files (from 'simple' dataset ) are attached.

[simple.chromInfo.txt](https://github.com/dputhier/pygtftk/files/3448027/simple.chromInfo.txt)
[simple_peaks.bed.txt](https://github.com/dputhier/pygtftk/files/3448028/simple_peaks.bed.txt)
[simple.gtf.txt](https://github.com/dputhier/pygtftk/files/3448029/simple.gtf.txt)

**Comment by dputhier** [comment]
The chromosome format must be numeric, I guess. We should think about adding a dataset with ensembl chromosome format for testing the commands.

**Comment by qferre** [comment]
I recreated this as well on my computer, with the same results. It is the other way around : *the chromosome format must not be numeric*. Ensembl format is causing problems, we will add a check-up early in the code to convert it to UCSC format automatically. @dputhier : I believe we ran into this error already, and it it scheduled for the next release of libgtftk, with automatic harmonization of chromosomes names ?

@Yghdrazill : if you add "chr" at the beginning of your chromosomes' names it should work.
To save you some time, here is a quick awk command you can copy-paste :
```
awk '$0="chr"$0' old.bed > new.bed
```

**Comment by dputhier** [comment]
I guess we should simply convert them to string. I can't see any problem
with that. We may talk together about that tomorrow.
Besr

Le mar. 30 juil. 2019 19:19, Quentin Ferré <notifications@github.com> a
écrit :

**Comment by Yghdrazill** [comment]
Hi, 

Sorry I was unavailable yesterday evening. Indeed my initial GTF set was without 'chr' for the chromosome column, so i have set all my annotation files without 'chr'. As i'm not familiar with this format I thought all chromosome columns should be without 'chr'...hence my mistake.

Denis, I don't need to answer any of those points anymore right ?
>     * For instance could you provide us with a skeleton of the command line used to call gtftk.
> 
>     * Also, it would be helpful to know about the chromosomes that are present or not in the GTF/BED/ChromInfo files so that we can try to recreate the issue.
> 
>     * Does the -fwq argument solve the issue ?

Thanks for your quick replies !! I'll put back a 'chr' for everything.

Léo

**Comment by dputhier** [comment]
This is fixed in 49d0c320231fab69bacc828998913942a10d1ac2.
Thanks a lot Léo for reporting this bug and help us improving pygtftk.
This fix will be available in the next release upcoming (1.0.9) otherwise in branche hotfix/1.0.9 (which is untested at the moment).
Best
