### ISSUE TITLE
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#108]
This warning during doc building:

		/Users/puthier/miniconda3/envs/pygtftk_test/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
		  return f(*args, **kwds)
		/Users/puthier/miniconda3/envs/pygtftk_test/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
		  return f(*args, **kwds)

**Comment by qferre** [comment]
Pretty sure that's not due to our code, and should have gone away in Python 3.8

**Comment by dputhier** [comment]
Let's close it for the moment.
