### ISSUE TITLE
git merge failure in ologram doc

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#115]
I  have noticed this git merge fail on the ologram doc:
https://dputhier.github.io/pygtftk/ologram.html#head
https://github.com/dputhier/pygtftk/blob/master/docs/source/ologram.rst#-head

Can I just :
1. edit the rst in master 
2. `make html` in docs
3. commit changes in master

Or the appropriate workflow is different?

**Comment by dputhier** [comment]
Yep. You may require some additional python packages to build.
Best
