### ISSUE TITLE
Ologram and py3.8

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#117]
Hi @qferre ,
Hope you are doing well. I was trying to fix issue #116 through a hotfix. I told myself that in the meantime it could be interesting to ensure compatibility with py3.8 (which is now the default for conda). I had one issue with multiproc complaining about some "__spec__" variable, but no matter, I fixed it (with an obscur workaround) in 0e94ae3ced59beb255808793e57677db76d5571f
Now I'm getting a strange behaviour with OLOGRAM. Installation throw several warning related to tp_print. More problematic, the time needed to create fake bed is multiplied by 10 (compared to what is observed with py3.6).
Could you have a look at branch hotfix/1.1.1 ?
Best

**Comment by qferre** [comment]
Hi Denis,

I'm fine, thanks! When you say multiproc, do you mean the Python "multiprocessing" module ?
I have not re-run the code yet, but in any case I have observed that my current use of multiprocessing is rather inefficient, so it may be what's causing the problem if there are new thread-safety measure guidelines in Python 3.8

Were the other running times more or less the same as usual ? It was only the time to create the fake beds ?

**Comment by dputhier** [comment]
Yes, I'm talking about multiprocessing module. I got this error (https://stackoverflow.com/questions/45720153/python-multiprocessing-error-attributeerror-module-main-has-no-attribute).
But I think that here the problem is not related. The think is that the code is working but it is 10x slower. I was wondering whether was properly cythonized (?).

**Comment by qferre** [comment]
That's possible. Could you send me the warnings you had about "tp_print" ? Apparently these errors have something to do with improper Cythonisation in Python 3.8 specifically : https://bugs.python.org/issue37250

Were other steps similarily slower or was it just "fake bed creation" ?

**Comment by dputhier** [comment]
Here is the output upon installation (as attached file).
I think only "fake bed creation" is impacted.

[pygtftk_py3.8_log.txt](https://github.com/dputhier/pygtftk/files/4438461/pygtftk_py3.8_log.txt)




╰─ gtftk -s

- pygtftk version : 1.1.1
- pygtftk path : /Users/puthier/miniconda3/envs/pygtftk3.8/lib/python3.8/site-packages/pygtftk-1.1.1-py3.8-macosx-10.9-x86_64.egg/pygtftk
- python version : sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
- python path : /Users/puthier/miniconda3/envs/pygtftk3.8
- pandas version : 1.0.3
- Bedtools version : bedtools v2.29.2
- pybedtools version : 0.8.1
- pyBigWig version : 0.3.17
- uname : posix.uname_result(sysname='Darwin', nodename='Denis-Mac-Book-2019.local', release='19.0.0', version='Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64', machine='x86_64')

**Comment by qferre** [comment]
I think improper Cythonization is indeed the problem. According to the log you sent, `create_shuffles.pxd`, the file involved in the fake bed creation, is the only one to throw a `tp_print` error, which would explain why it's the only one affected.

I am starting to worry that this is a Cython issue and not something we can fix on our end...

**Comment by qferre** [comment]
I checked the log again, and `create_shuffled.pxd` is not the only one to send `tp_print` errors, the file `read_bed_as_list.cpp` does as well. Could you tell me if the very first time, the time to read bed files, is also increased ?

But in any case those errors should not have much of an impact (see https://github.com/cython/cython/issues/3474) ? I fear the problem is elsewhere with Cython and that it is not something I can fix...

**Comment by qferre** [comment]
I checked the source. The lines of code throwing those errors are for functions that are not used by default (for Markov shuffling and concatenation of excluded regions). Were you using region exclusion in your tests ?

If not, it is likely we are dealing with a silent error somewhere deep in Cython and/or Python 3.8

**Comment by dputhier** [comment]
Did you try to install a py3.8 env and go for a test ? I think this would
be important for you to try to debug. I observed this under OSX. The first
think would be to know whether this is also observed under Linux. I really
think that we have to go for a workaround as 3.8 will quickly become the 3k
standard (as was 2.7 for 2k). So it is critical that we pass all test with
this version.
Best

Le ven. 10 avr. 2020 à 18:11, Quentin Ferré <notifications@github.com> a
écrit :

**Comment by qferre** [comment]
Could you send me your specifications as a yaml for the 3.8 environment ? I have conflicts when I try to use the default one (travis_env.yaml) in the hotfix branch. I've been trying to solve them all day but it seems to affet several packages.

**Comment by dputhier** [comment]
I'm on latest conda version (which relies on py3.8) and in hotfix/1.1.1 branch.
The env.yaml is attached.
[env_pygtftk_1.1.1.yaml.txt](https://github.com/dputhier/pygtftk/files/4466012/env_pygtftk_1.1.1.yaml.txt)

Best.
╰─ conda --version
conda 4.8.3
╰─ conda activate pygtftk3.8
╰─ make install # which should complete
╰─ conda env export > ~/Downloads/env_pygtftk_1.1.1.yaml

**Comment by qferre** [comment]
Never mind, I fixed my dependencies problem through manual installations using pip. Unorthodox, but it will do.

To the matter at hand : I was unable to reproduce that error. Using randomly generated BED files, the running times between Python 3.6 and 3.8 are almost identical on an Ubuntu 18.04 machine...

Is there any chance your RAM usage was high when you ran the test ? I found out it can artificially inflate processing time without returning an error.

**Comment by dputhier** [comment]
I said something wrong, the latest conda version does not rely on py3.8.
I tried also under linux, and it works well. This one is OSX related... To be continued...

**Comment by dputhier** [comment]
Just for info, the time required under py3.6 and py3.8 under OSX...
 
        gtftk get_example -d simple_02 -f '*'
        rm -Rf ologram_output; time gtftk ologram -V 3 -i simple_02.gtf -p simple_02_peaks.bed -c simple_02.chromInfo -u 2 -d 2 -K ologram_output --no-date -k 8

**py3.8:**

1091.77s user 
900.49s system 
693% cpu 
4:47.24 total

**py3.6:**

34.33s user 
19.10s system 
124% cpu 
42.883 total

**Comment by dputhier** [comment]
3.6 and 3.7 behave the same:

**py3.7:**
34.52s user 
20.25s system 
125% cpu 
43.720 total
