### ISSUE TITLE
Ologram fails when testing overlaps in genomic subset

### ISSUE THREAD

**Issue by DimKat** [dputhier/pygtftk#121]
Hello,

I have been using ologram to test for the significance of overlaping sets of intervals produced by DNA-protein interaction assays and so far I have found it very useful and easy to implement with multiple different settings. I mostly use the -z and -b options since I am overlaping experimental peak data between them. I recently  tried to run ologram for intervals that I expected not to be homogeniously distributed across the genome but to be mostly concentrated in promoter regions. To that end I used the -bi option and a .bed file containing all promoters of the genome (around 20 K sets of genomic coordinates) to be used to concatenate the genome and peak files and adjust the calculation for overlaps within those sequences. I know by intersecting my shortened peak files in bedtools that I should be expecting over a thousand observed intersections for my two interval files but ologram reproducibly only finds 6 real intersections and 60 base pairs of overlap. It does, however, give me the following warning before finishing:

|-- 14:23-WARNING-ologram : interval_setB: there may be a poor fit for this feature. Check fit quality in the results. This is likely due to there being too few regions.

Intrestingly, using a different feature bed file (for -b) or a whole different combination of interval sets again gives me exactly the same number of intersections and bp of overlap.  I have the same outcome when instead of -bi I use -e to exclude sequences. 
I have read in your documentation that excluded sequence files need to be of about 1000 intervals which I guess might have to do with the limits of processing capacity (?). The peculiar thing is that ologram fails to identify the correct number of observed/real intersections not just to estimate intersections in the shuffled simulated dataset. ]
For all the above I have used ologram Version:  2019-04-17 in gtftk v1.1.0 on an Ubuntu virtual machine running in a windows 7 host.
I have attached relevant files below for issue replication
[ologram github question.zip](https://github.com/dputhier/pygtftk/files/4676656/ologram.github.question.zip)

Let me know if there is any other details I need to provide or if I haven't made anything clear and sorry for the long explanation and the format I am a mostly experimental biologist.

Thank you in advance.

**Comment by dputhier** [comment]
Hi DimKat. Thank you for your interest in OLOGRAM, for your feedback and providing us with example files. We will have a look at this issue and come back to you asap.
Best

**Comment by dputhier** [comment]
Dear Dimkat,
First, regarding the warning message ("there may be a poor fit for this feature") this can be observed in some cases depending on the structure of the dataset. This indicates that the program is unable to properly fit the distribution (derived from genomic region shuffling) using a negative binomial model. In this case the program indicates that it is not confident with the provided p-value. To overcome this one may try to increase the number of shufflings (mainly through --minibatch-nb). Otherwise alternative methods (e.g. without fitting) should be used (e.g see Genomic HyperBrowser). Note that, in the example below, I am not getting this warning (maybe we are not using exactly the same command line).

I'm using here the same version of pygtftk (1.1.0) on a mac OSX computer. 

     gtftk ologram -z -b interval_setB.bed -bi  Genomic_sequences_to_include_merge.bed   -p interval_setA.bed --chrom-info t.genome  -D -k 12  -l test

On my side I am getting the following output which seems to indicate that there are 837 observed intersections.

      gtftk col_from_tab -i ologram_output/00_ologram_stats.tsv -c nb_intersections_true,nb_intersections_expectation_shuffled
     nb_intersections_true	nb_intersections_expectation_shuffled
     837	81.5

When I try to compute the number of intersections occuring between set A and B in "Genomic_sequences_to_include.bed" I am getting the following result:

     bedtools intersect -a interval_setA.bed -b Genomic_sequences_to_include.bed | sortBed | mergeBed > interval_setA_to_include.bed
     bedtools intersect -a interval_setB.bed -b Genomic_sequences_to_include.bed | sortBed | mergeBed > interval_setB_to_include.bed
     bedtools intersect -a interval_setA_to_include.bed -b interval_setB_to_include.bed | wc -l
     842

So, if I'm not wrong, in the current example the number of intersection computed using Bedtools is 842 and we have computed 837 (note that all regions are merged internally by ologram). While there is a slight difference (which may be perhaps related to a small implementation difference/issue in one of the two programs).

Could you elaborate more on your example. Could you check the call to ologram is the same (except -D argument, -k/--nb-threads and -l) ?

**Comment by DimKat** [comment]
Dear dputhier,

My command line was:

`gtftk ologram -z -c t.genome -p interval_setA.bed -b interval_setB.bed -l test -bi Genomic_sequences_to_include.bed -k 4`

Having seen your line and following your advice I also tried to premerge the inclusion bed or increase the minibatch number (-mn 100 and 1000) to prevent the warning message from appearing but got the same outcome (again warning message and only 6 intersections). The output for all 3 attempts is attached
[ologram_output.zip](https://github.com/dputhier/pygtftk/files/4677557/ologram_output.zip)

When I test for the number of intersections with bedtools I get 838. I use the -u setting when intersecting with the included genomic sequences such that an interval is not reported more than once if it overlaps.

Is there any dependency called by ologram that I could be missing which does not prevent running of the command/algorithm but missprocesses the data on my set up? Or a linux vs OS X difference?

Thank you for your interest and help

**Comment by dputhier** [comment]
Could you provide us with the output of:

      gtftk -s

Best

**Comment by DimKat** [comment]
Sure. 

`$ gtftk -s

- pygtftk version : 1.1.0
- pygtftk path : /home/dimitris/miniconda3/envs/pygtftk/lib/python3.7/site-packages/pygtftk
- python version : sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
- python path : /home/dimitris/miniconda3/envs/pygtftk
- pandas version : 1.0.0
- Bedtools version : bedtools v2.29.2
- pybedtools version : 0.8.1
- pyBigWig version : 0.3.17
- uname : posix.uname_result(sysname='Linux', nodename='dimitris-VirtualBox', release='4.15.0-101-generic', version='#102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020', machine='x86_64')`

I hope this helps.

**Comment by dputhier** [comment]
Got it...
This one is related to an issue in pandas. I'm currently using pandas version 0.25.3 that precedes 1.0.0rc0 and it works. If you use 1.0.0rc0 or  1.0.0 you will get the bug. If you upgrade to pandas 1.0.1, 1.0.2 or 1.0.3 it should work again.

So I would advise to go for pandas 1.0.3

     pip install pandas==1.0.3

Backward compatibilities are (really too) frequent in pandas... I will upgrade the code (i) to avoid usage of 1.0.0rc0 and 1.0.0 upon installation but also (ii)  to impede gtftk with these pandas version. 

Tell me if it fixes the issue on your system.

Thank you again for your interest and for the feedback

**Comment by DimKat** [comment]
Great! 

This fixed the issue and it is working perfectly now. I get the expected observed intersections and the warning message does not appear anymore either.

Thank you very much for your speedy help with this. I appreciate it. 

Kind regards, 

Dimitris
