### ISSUE TITLE
ologram_modl_treeify_1 test error:  add graphviz as a dependency in the conda build

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#126]
We have to think about adding graphviz as a dependency in the conda build

		not ok 18 ologram_modl_treeify_1
		# (in test file ologram.bats, line 70)
		#   `result=`gtftk ologram_modl_treeify -i multiple_overlap_trivial_ologram_stats.tsv -o tree_multi.pdf -l QueryLabel`' failed
		#  |-- 11:06-INFO : Checking configuration file.
		# Traceback (most recent call last):
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/graphviz-0.14.1-py3.7.egg/graphviz/backend.py", line 164, in run
		#     proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
		#   File "/Users/puthier/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
		#     restore_signals, start_new_session)
		#   File "/Users/puthier/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
		#     raise child_exception_type(errno_num, err_msg, err_filename)
		# FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'
		#
		# During handling of the above exception, another exception occurred:
		#
		# Traceback (most recent call last):
		#   File "/Users/puthier/anaconda3/bin/gtftk", line 4, in <module>
		#     __import__('pkg_resources').run_script('pygtftk==1.1.5', 'gtftk')
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
		#     self.require(requires)[0].run_script(script_name, ns)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
		#     exec(code, namespace, namespace)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 104, in <module>
		#     args = main()
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/gtftk", line 89, in main
		#     CmdManager.run(args)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/pygtftk/cmd_manager.py", line 959, in run
		#     fun(**args)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/pygtftk/plugins/ologram_modl_treeify.py", line 89, in ologram_modl_treeify
		#     tree.output_visualize(L, output.name)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/modl/tree.py", line 481, in output_visualize
		#     s.render(output_path, format = 'pdf', view=False, cleanup = True)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/graphviz-0.14.1-py3.7.egg/graphviz/files.py", line 209, in render
		#     quiet=quiet)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/graphviz-0.14.1-py3.7.egg/graphviz/backend.py", line 221, in render
		#     run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
		#   File "/Users/puthier/anaconda3/lib/python3.7/site-packages/graphviz-0.14.1-py3.7.egg/graphviz/backend.py", line 167, in run
		#     raise ExecutableNotFound(cmd)
		# graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'tree_multi'], make sure the Graphviz executables are on your systems' PATH

**Comment by guillaumecharbonnier** [comment]
All bats tests pass with v1.2.0
https://github.com/bioconda/bioconda-recipes/commit/ebe72cb02dc1a94677c85a50f361b7097ff6a712
