### ISSUE TITLE
ologram_modl_treeify_1 test error: wrong output under OSX

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#127]
The expected result is "" but the output is:

	╰─ gtftk ologram_modl_treeify -i multiple_overlap_trivial_ologram_stats.tsv -o tree_multi.pdf -l QueryLabel
	 |-- 11:34-INFO : Checking configuration file.
	00000
	11001
	11101
	11111

**Comment by dputhier** [comment]
Note that all other tests are passing under OSX (but this failure impedes the ending of the testing process).

**Comment by qferre** [comment]
Should have been fixed in commit 0878f99.
Does it work for you ?

**Comment by dputhier** [comment]
Yes @qferre. This seems ok now.
