### ISSUE TITLE
ModuleNotFoundError: No module named 'cython'

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#129]
After a fresh conda installation and a fresh pygtftk installation I got the following message which seem to indicate that cython is not part of bioconda build dependency...

**Comment by guillaumecharbonnier** [comment]
Why do you want cython as a requirement in the run environment?
It is already in the build environment and all tests are passing in the run environment.

**Comment by dputhier** [comment]
OK. I had no time to check it last time. Should be OK. Closing.
