### ISSUE TITLE
several warnings when building docs [develop branch]

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#130]
Seems that paths to some modules need to be updated

		WARNING: autodoc: failed to import module 'overlap_stats_compute' from module 'pygtftk.stats.intersect'; the following exception was raised:
		No module named 'pygtftk.stats.intersect.overlap_stats_compute'
		WARNING: autodoc: failed to import module 'negbin_fit' from module 'pygtftk.stats'; the following exception was raised:
		No module named 'pygtftk.stats.negbin_fit'
		WARNING: autodoc: failed to import module 'beta' from module 'pygtftk.stats'; the following exception was raised:
		No module named 'pygtftk.stats.beta'
		WARNING: autodoc: failed to import module 'modl.tree' from module 'pygtftk.stats.intersect'; the following exception was raised:
		No module named 'pygtftk.stats.intersect.modl'
		WARNING: autodoc: failed to import module 'modl.dict_learning' from module 'pygtftk.stats.intersect'; the following exception was raised:
		No module named 'pygtftk.stats.intersect.modl'
		WARNING: autodoc: failed to import module 'modl.subroutines' from module 'pygtftk.stats.intersect'; the following exception was raised:
		No module named 'pygtftk.stats.intersect.modl'

**Comment by qferre** [comment]
I think these are actually the correct paths. In any case, I can run `import pygtftk.stats.intersect.modl` in Python without problems.
I also do not have this error when I run `make doc`. 

If you run `import pygtftk.stats.intersect.modl` in Python in the same environment you use to build the doc, is there an exception raised ?

**Comment by dputhier** [comment]
It seems that some path are wrong. For instance the first error is related to pygtftk.stats.intersect.overlap_stats_compute:

		╰─ ipython
		Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)
		Type 'copyright', 'credits' or 'license' for more information
		IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

		In [1]: from pygtftk.stats.intersect import overlap_stats_compute
		---------------------------------------------------------------------------
		ImportError                               Traceback (most recent call last)
		<ipython-input-1-63c7a54af24a> in <module>
		----> 1 from pygtftk.stats.intersect import overlap_stats_compute

		ImportError: cannot import name 'overlap_stats_compute' from 'pygtftk.stats.intersect' (/Users/puthier/miniconda3/envs/pygtftk_dev/lib/python3.7/site-packages/pygtftk/stats/intersect/__init__.py)




![image](https://user-images.githubusercontent.com/1831198/91458363-ba2c9600-e885-11ea-95b4-f6c662321a64.png)

**Comment by dputhier** [comment]
OK. Got it. Several versions of pygtftk in ...python3.7/site-packages...
