### ISSUE TITLE
ologram.rst:198: WARNING: Error in "command-output" directive: 	1 argument(s) required, 0 supplied.

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#131]
The command should be written on the same line as ".. command-output::", I guess.... Need to be tested...

	/Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:198: WARNING: Error in "command-output" directive:
	1 argument(s) required, 0 supplied.

	.. command-output::

	  gtftk ologram -z -c simple_07.chromInfo -p simple_07_peaks.bed       # The query (-p) is the file to compare against.
	      --more-bed simple_07_peaks.1.bed simple_07_peaks.2.bed           # List of files to compare with
	      # --more-bed `ls -d ./data/*`                                    # This should work instead if all your files are in the 'data' subdirectory
	      -o results --force-chrom-peak --force-chrom-more-bed
	      -V 3 -k 8 -mn 10 -ms 10                                          # Verbosity, threads, number and size of minibatches
	      --more-bed-multiple-overlap                                      # Use multiple overlaps on the --more-bed
	      --multiple-overlap-max-number-of-combinations 10                 # OPTIONAL ARGUMENT. Use MODL to restrict to this many combinations.
	      --multiple-overlap-target-combi-size 3                           # OPTIONAL ARGUMENT. Combis mined longer than this size will not be shown.
	      --multiple-overlap-custom-combis test_combis.txt                 # OPTIONAL ARGUMENT. Will bypass the selection by the previous two arguments and work only on the combinations defined in this file.
	  :shell:

**Comment by qferre** [comment]
I'll try.
Is it possible to go to the next line in command-output or do I have to write everything on the same line ? So I know if I can write comments or not.

**Comment by dputhier** [comment]
Don't know... Maybe you could use backslash...

Le jeu. 27 août 2020 à 15:48, Quentin Ferré <notifications@github.com> a
écrit :

**Comment by qferre** [comment]
I think I will instead make a simple example with no comments, and a complex example that will not be run. I'm on it.
