### ISSUE TITLE
ologram.rst:247: WARNING: Error in "code-block" directive:   maximum 1 argument(s) allowed, 20 supplied.

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#132]
Another warning that appear upon doc building.
 
    /Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:247: WARNING: Error in "code-block" directive:
    maximum 1 argument(s) allowed, 20 supplied.

    .. code-block:: python
      from pygtftk.stats.intersect.modl.dict_learning import Modl, test_data_for_modl
      flags_matrix = test_data_for_modl(nflags = 1000, number_of_sets = 6, noise = 0.1, cor_groups = [(0,1),(0,1,2,3),(4,5)])

      from pygtftk import utils
      utils.VERBOSITY = 2 # Ensure DEBUG messages are shown

      combi_miner = Modl(flags_matrix,
            multiple_overlap_target_combi_size = -1,    # Limit the size of the combinations
            multiple_overlap_max_number_of_combinations = 3,    # How many words to find ?
            nb_threads = 1,
            step_1_factor_allowance = 2, # How many words to ask for in each step 1 rebuilding
            error_function = None)    # Custom error function in step2
      interesting_combis = combi_miner.find_interesting_combinations()
    /Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:352: WARNING: Error in "code-block" directive:
    maximum 1 argument(s) allowed, 17 supplied.

**Comment by qferre** [comment]
I think this is due to not jumping a line between `.. code-block:: python` and the rest. Investigating.

**Comment by qferre** [comment]
I pushed 1ed828f, does it fix the issue ?
