### ISSUE TITLE
Remaining warnings in doc 

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#133]
@qferre Il reste ce probème concernant ologram dans la doc.

    /Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:155: WARNING: Error in "code-block" directive:
    maximum 1 argument(s) allowed, 20 supplied.

    .. code-block:: bash
            gtftk ologram -ms 40 -mn 10 -p query.bed --more-bed A.bed B.bed C.bed -z -c hg38 -V 3 --force-chrom-peak --force-chrom-more-bed
    /Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:190: WARNING: Inline strong start-string without end-string.
    /Users/puthier/Documents/git/project_dev/pygtftk/docs/source/ologram.rst:361: WARNING: Error in "code-block" directive:
    maximum 1 argument(s) allowed, 17 supplied.

    .. code-block:: bash
      # Make several OLOGRAM runs
      N_RUNS = 100
      for i in {1..$N_RUNS}
      do
        ologram ...
      done

      # Merge those runs
      gtftk ologram_merge_runs --inputfiles `ls ./results/*.tsv` -o ./merged_batches_result.tsv -V 3

**Comment by dputhier** [comment]
Also one in dict_learning:

		/Users/puthier/miniconda3/envs/pygtftk_dev/lib/python3.7/site-packages/pygtftk-1.1.5-py3.7-macosx-10.9-x86_64.egg/pygtftk/stats/intersect/modl/dict_learning.py:docstring of pygtftk.stats.intersect.modl.dict_learning.squish_matrix:4: WARNING: Definition list ends without a blank line; unexpected unindent.

**Comment by qferre** [comment]
For the first two, those are the usual case: I forgot to add a blank line at the beginning of the code block. For the last one, it was due to me using indents in a docstring.

Both should be fixed in 28e28cf. Is it OK for you ?
