### ISSUE TITLE
warning upon installation

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#135]
Could it be possible to fix so that we get ride of this message upon installation (at least under OSX)

		/pygtftk_dev/include/python3.7m -c pygtftk/stats/multiprocessing/multiproc.c -o build/temp.macosx-10.9-x86_64-3.7/pygtftk/stats/multiprocessing/multiproc.o -W -O3 -Wno-#warnings
		pygtftk/stats/multiprocessing/multiproc.c:2369:31: warning: code will never be executed [-Wunreachable-code]
		                if ((1 == 0)) abort();
		                              ^~~~~
		pygtftk/stats/multiprocessing/multiproc.c:2369:22: note: silence by adding parentheses to mark code as explicitly dead
		                if ((1 == 0)) abort();
		                     ^
		                     /* DISABLES CODE */ ( )
		pygtftk/stats/multiprocessing/multiproc.c:2712:97: warning: unused function '__pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_example_func' [-Wunused-function]
		static struct __pyx_t_7pygtftk_5stats_15multiprocessing_17multiproc_structs_FUNC_2DARRAY_RESULT __pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_example_func(PY_LONG_LONG *__pyx_v_arr, PY_LONG_LONG *__pyx_v_shape, PY_LONG_LONG __pyx_v_parameter) {
		                                                                                                ^
		pygtftk/stats/multiprocessing/multiproc.c:2888:18: warning: unused function '__pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_printcustom' [-Wunused-function]
		static PyObject *__pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_printcustom(struct __pyx_t_7pygtftk_5stats_15multiprocessing_17multiproc_structs_FUNC_2DARRAY_RESULT __pyx_v_result) {
		                 ^
		3 warnings generated.

**Comment by qferre** [comment]
I'm unsure. Those specific lines do not seem to be code that I have written, it's generated by Cython. I'll look into it.

**Comment by dputhier** [comment]
This one seems to be fixed with Python 3.9. Closing.
