### ISSUE TITLE
Conda installation not working

### ISSUE THREAD

**Issue by amathelier** [dputhier/pygtftk#140]
I tried to install pygtftk following the readme comments but got the following error:
`$ conda create -n pygtftk -c bioconda pygtftk`

> Fetching package metadata .............
> Solving package specifications: 
> 
> InvalidSpecError: Invalid spec: =20190808
>

**Comment by dputhier** [comment]
Thank you Anthony for your feedback and your interest in pygtftk. IGot the same on Linux... In fact, we are experiencing problems with the last bioconda release of pygtftk. It is working under OSX  (but provides an older version). We will try to fix that asap.
@guillaumecharbonnier any idea ?

**Comment by guillaumecharbonnier** [comment]
On Linux, you need to have conda-forge, bioconda et defaults channels in this strict order in your `~/.condarc`.

Alternatively, you can create your environnment using yaml file like this one:
`conda env create -f pygtftk.yaml`

where pygtftk.yaml contains:
```
name:
  pygtftk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pygtftk
```

To get a recent version on macOS, you should append the channel `guillaume charbonnier` below the `defaults` in the yaml. Until https://github.com/dputhier/pygtftk/issues/139 is solved...

**Comment by dputhier** [comment]
@guillaumecharbonnier I got the same issue...
Did you tried on your side ?

	$ conda env create -f pygtftk.yaml
	Fetching package metadata ...................
	Solving package specifications:

	InvalidSpecError: Invalid spec: =20190808

	$ cat pygtftk.yaml
	name:
	  pygtftk
	channels:
	  - conda-forge
	  - bioconda
	  - defaults
	dependencies:
	  - pygtftk

**Comment by amathelier** [comment]
It might be a conda version issue (not sure). I was able to install on one of my machine (Ubuntu 18.04) but not on the other (el7). Two different versions of conda were used: conda 4.3.21 (not working) and conda 4.8.5 (working). Not sure if it helps.

**Comment by guillaumecharbonnier** [comment]
Yes I tried first before answering, conda 4.7.12 here.
After conda update everything is ok?

**Comment by amathelier** [comment]
I cannot update conda for now because it is on our HPC that is used by many users.

**Comment by guillaumecharbonnier** [comment]
In the meantime or if they have reason not to update, you can install miniconda in your own folder and use the latest conda version.

**Comment by dputhier** [comment]
Updating conda using "conda update conda" did also the trick for me. Thank you @amathelier  for the workaround. I will close this issue that seems more to be related to conda. Feel free to re-open it if needed. 
Best
Denis
