### ISSUE TITLE
some typo and remarks and ologram

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#148]
Hi @qferre ,
Just few very minor improvement about displays when ologram is running :
- Combination 63/69done -> add a space.
- Negative Binomial distributions fitted in : 2.717513084411621 s -> Maybe we do not need that level of precision :)
Best

**Comment by dputhier** [comment]
Also "Computing and true intersections..."

**Comment by qferre** [comment]
Fixed in commit fd6d879.
