### ISSUE TITLE
ERROR-mk_matrix with conda packaged version of release 0.9.1

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#15]
The first conda package for pygtftk is out:
https://anaconda.org/guillaumecharbonnier/pygtftk
I am not able to pass tests requiring this file though:
`ERROR-mk_matrix : Not a bigwig file :pygtftk/data/simple/simple.bw`

Maybe an issue with the version of pyBigWig?
```
            bigwig = pyBigWig.open(big_wig)
            if not bigwig.isBigWig():
                message("Not a bigwig file :" + big_wig, type="ERROR")
```
Version of pybigwig in packaged environment:
https://conda.anaconda.org/bioconda/linux-64/pybigwig-0.2.8-py27_0.tar.bz2

Version of pybigwig in working unpackaged environment:
https://conda.anaconda.org/bioconda/linux-64/pybigwig-0.3.10-np113py27_0.tar.bz2

Currently rebuilding with higher-version requirement to see if it solves the issue.

**Comment by dputhier** [comment]
0.9.4 is out. Pygtftk now requires pyBigWig 0.3.12. I think it would fix this issues... Let see. Test 'random_tx_7' passed on both OSX and Ubuntu 12.04.
