### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#151]
@qferre did you manage to install pygtftk v1.2.8 on sacapus ?

**Comment by qferre** [comment]
Yeah, it works now. Does it work for you ?

**Comment by dputhier** [comment]
You should change your name if you want to develop robust code :)

		$ make install
		/bin/sh: gtftk: command not found
		/bin/sh: gtftk: command not found
		  File "setup.py", line 49
		SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 49, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by qferre** [comment]
That seems a little bit racist :P
Maybe we can just put it in capitals, no accent ?

**Comment by dputhier** [comment]
Yep :)

Le jeu. 1 avr. 2021 à 12:09, Quentin Ferré ***@***.***> a
écrit :

**Comment by qferre** [comment]
Done in commit 2c1c8d4

**Comment by dputhier** [comment]
It seems that some non ascii characters were introduced in the README file.

    3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
    Python version : sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
    Python path : /Softs/tagc/denis/conda/conda/envs/pygtftk_py3k
    Traceback (most recent call last):
      File "setup.py", line 221, in <module>
        long_description = open('README.rst', mode="r").read()
      File "/Softs/tagc/denis/conda/conda/envs/pygtftk_py3k/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4145: ordinal not in range(128)


E.g. the ... in:
- Gene centric features enclosed in a GTF (e.g. exons, promoters, terminators…).

Il will fix and push.
