### ISSUE TITLE
tp_vectorcall

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#155]
Fresh python 3.8 under sacapus. Got these warnings

          gcc -pthread -B /Softs/tagc/denis/conda/conda/envs/python_38/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/Softs/tagc/denis/conda/conda/envs/python_38/lib/python3.8/site-packages/numpy/core/include -I/Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8 -c pygtftk/stats/intersect/overlap/overlap_regions.c -o build/temp.linux-x86_64-3.8/pygtftk/stats/intersect/overlap/overlap_regions.o -W -O3 -fopenmp -Wno-cpp
          pygtftk/stats/intersect/overlap/overlap_regions.c:25489:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall' declared here
               vectorcallfunc tp_vectorcall;
                              ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:25597:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall' declared here
               vectorcallfunc tp_vectorcall;
                              ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:25847:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall' declared here
               vectorcallfunc tp_vectorcall;
                              ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:25982:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall' declared here
               vectorcallfunc tp_vectorcall;
                              ^
          pygtftk/stats/intersect/overlap/overlap_regions.c: In function '__Pyx_modinit_type_init_code':
          pygtftk/stats/intersect/overlap/overlap_regions.c:26714:3: warning: 'tp_print' is deprecated (declared at /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
             __pyx_type___pyx_array.tp_print = 0;
             ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:26719:3: warning: 'tp_print' is deprecated (declared at /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
             __pyx_type___pyx_MemviewEnum.tp_print = 0;
             ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:26734:3: warning: 'tp_print' is deprecated (declared at /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
             __pyx_type___pyx_memoryview.tp_print = 0;
             ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:26747:3: warning: 'tp_print' is deprecated (declared at /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
             __pyx_type___pyx_memoryviewslice.tp_print = 0;
             ^
          pygtftk/stats/intersect/overlap/overlap_regions.c: At top level:
          pygtftk/stats/intersect/overlap/overlap_regions.c:31385:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall' declared here
               vectorcallfunc tp_vectorcall;
                              ^
          pygtftk/stats/intersect/overlap/overlap_regions.c:31739:1: warning: missing initializer for field 'tp_vectorcall' of 'PyTypeObject' [-Wmissing-field-initializers]
           };
           ^
          In file included from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/object.h:746:0,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/pytime.h:6,
                           from /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/Python.h:85,
                           from pygtftk/stats/intersect/overlap/overlap_regions.c:4:
          /Softs/tagc/denis/conda/conda/envs/python_38/include/python3.8/cpython/object.h:257:20: note: 'tp_vectorcall

**Comment by qferre** [comment]
Apparently, we don't have to worry about this.
Source: https://bitbucket.org/wlav/cppyy/issues/186/warnings-with-python-38-due-to-vectorcall

Additionally, I do not get this warning on my computer, so I assume it is simply due to Sacapus' version of gcc being too old. 
Source: https://stackoverflow.com/questions/1538943/why-is-the-compiler-throwing-this-warning-missing-initializer-isnt-the-stru
