### ISSUE TITLE
OLOGRAM: exclusive combinations

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#157]
Hi @qferre,
I dont understand why setting  -mocs to --more-bed +1 give exact combination (I guess this is length(--more-bed) + 1). If reference regions are A,B,C I could be interested in query+X+Y in exact mode but not query+X+Y+Z. My feeling is that a second argument controlling exact/inexact would be required. But there is maybe something I missed...

**Comment by qferre** [comment]
Hi Denis,

You are right, there is not good reason why this is so. It is an artifact of the way I implemented exact and inexact counting in the code, it was simpler to write the arguments like this at the time.

I should give a separate argument for exact and inexact. I'll get on it as soon as I can.

**Comment by qferre** [comment]
Working on it right now. I am making some more backend changes (exposing additional parameters in MODL's API) and I'll push it along with the rest, once all the unitary tests pass.

**Comment by qferre** [comment]
Fixed in 2731a7fe471801d377b6ccf0faa6fb856d12484d.
