### ISSUE TITLE
Distutils package at installation - 'ftputils'

### ISSUE THREAD

**Issue by qferre** [dputhier/pygtftk#17]
During installation with the `pip install pygtftk` command, an error occurs when trying to uninstall ftputils 3.2, presumably to install a pygtftk-compatible version :

"Cannot uninstall 'ftputil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

*Workaround* : calling the installation with `pip install --ignore-installed pygtftk` results in pip skipping the package and installing correctly pygtftk, but this is not a viable solution as it will lead to older packages being kept and could result in a dependency error.

**Comment by dputhier** [comment]
Thanks for the workaround. It will be part of future works to improve pygtftk installation. This won't be an easy task given the various versions of Python / pip and each dependent packages. We are working on providing a conda package that will come in the near future and provide users with a more robust installation procedure.
Best
