### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by rongrongy** [dputhier/pygtftk#186]
conda create -n pygtftk pygtftk
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \

**Comment by dputhier** [comment]
Hi,
This is working on my side.

               conda create -n pygtftk_3.9k pygtftk python=3.9
               conda activate pygtftk_3.9k
               gtfk

Best

**Comment by dputhier** [comment]
I'm closing the issue. Feel free to reopen it if needed.
Best
