### ISSUE TITLE
Loosen dep requirements

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#23]

**Comment by guillaumecharbonnier** [comment]
Now that I have a conda version passing all tests during build time I can spend some time testing requirements. 
I wrote these in my todo to test :
- [ ] Pybigwig < 0.3.12
- [ ] Bedtools <= instead of ==
- [ ] Matplolib < 3
- [ ] Biopython to remove
- [ ] Cython to remove

**Comment by dputhier** [comment]
- Pybigwig: should be >= 0.3.12 at least in the requirements.txt (otherwise it has installation issue through pip). Maybe any version will be OK through a conda installation.

- Bedtools: I guess this is OK but I have no time to check it at the moment... If you had any time maybe you could run the test with Bedtools < and >.

- Matplotlib: I think that it should work with 2 and 3 (this is a plotnine dependency). The only thing is that matplotlib > 3 prints some deprecation warnings.

- Biopython: is required in fasta_interface.transcript_as_bioseq_records(). So it should be kept. The dependency can be checked by using make nose (or make nose_travis maybe) as it will run unitary tests available for lots of functionand/or methods.

- Cython: There is no direct need for Cython at the moment (I added it because one package, pysam if I remember well, had installation issues).

**Comment by guillaumecharbonnier** [comment]
Yes, I wanted to log my tests in this issue. So far, tests are passing in these conditions:
:heavy_check_mark: without cython
:x: without biopython
:heavy_check_mark: bedtools:             2.27.0-he941832_2                    bioconda
