### ISSUE TITLE
peak_anno complains about hg38.genome no existing but too late 

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#57]
I will have a look at this one.
DP
 
      gtftk get_example -d mini_real | gtftk peak_anno -p ENCFF112BHN_H3K4me3_K562_sub.bed -c hg38.genome -u 1500 -d 1500 -D  -if example_pa_01.pdf -V 3

**Comment by qferre** [comment]
I have not encountered this error when trying myself, any news ?

**Comment by dputhier** [comment]
Could not reproduce this one. Closing.
