### ISSUE TITLE
[peak_anno] Name change

### ISSUE THREAD

**Issue by qferre** [dputhier/pygtftk#65]
As we discussed, we should change the name of the tool to avoid confusion with another library.
Here are some of the proposals we discussed :

- stat_overlap
- feature_overlap
- feature_enrich
- peak_overlap
- peak_enrich

@dputhier, @guillaumecharbonnier, @Norisad , and others : Feel free to add some proposals of names ! We should decide soon so we can change the name on the paper as well.

**Comment by dputhier** [comment]
- PORtrAY --  Peak OveRlap AnalYsis
- POLArIty -- Peak OverLap AnalysIs
- POLAroId -- Peak OverLap AnalysIs
- BuFFALo -- Bed File Functionnal AnaLysis
- GROOVY -- Genomic RegiOns OVerlap analYsis
- METAFORE - METa Annotation For genOmic REgions  
- TAPiOcA -- Thorough Analysis of Peak OverlAp
- SALvAdOR -- Statistical AnaLysis peAk OveRlaps
- TORERO -- Testing OveRlap gEnomic RegiOns
- OLOGRAm -- OverLap Of Genomic Regions Analysis
- FLANGER -- FunctionaL ANalysis of GEnomic Region
...

http://acronymcreator.net/ace.py













-- | --






-- | --






-- | --

**Comment by qferre** [comment]
*This website is officially the best thing ever.*

I really like these (favorite at the top) :

- GROOVY -- Genomic RegiOns OVerlap analYsis
- POLArIty -- Peak OverLap AnalysIs
- OLOGRAm -- OverLap Of Genomic Regions Analysis

**Comment by dputhier** [comment]
Maybe OLOGRAm is the best regarding existing projects. Would be nice to find some meaning for the 'm'... :)

**Comment by qferre** [comment]
'M' could stand for Monte Carlo ?

**Comment by dputhier** [comment]
Yep.
OLOGRAm  -- OverLap Of Genomic Regions Analysis using Monte Carlo ?

**Comment by qferre** [comment]
That's going to be funny with the 'C' in Monte Carlo still capitalized in the title even though it's not part of the acronym XD.

Joke aside, I really like it.

**Comment by qferre** [comment]
Please do ! If I do it in Atom, I might break something. :)

I'll take care of the article draft.

**Comment by dputhier** [comment]
Changed to ologram in fe0468d3b485b2205ff9f30706d1e89a8f55a586

**Comment by qferre** [comment]
The change has been done on the draft as well. As such, I am closing this issue :)
