### ISSUE TITLE
provide user with default exclude regions. 

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#74]
Requires to get this regions. Could be a mappability tracks. Which word sizes ?

**Comment by qferre** [comment]
I am still a bit iffy about that. As you said, it requires settling on a standard word size, as well as a cutoff for the bigwig mappability signal.

Perhaps we could leave this decision to the user ?

**Comment by qferre** [comment]
I am closing this since while discussing it directly we elected to indeed leave this decision to the user.
