### ISSUE TITLE
[ologram]: FutureWarnings ...

### ISSUE THREAD

**Issue by YasmineKzl** [dputhier/pygtftk#75]
After updating (with the command git pull ..) and launching this command
` gtftk ologram -i Global_gtf_ensbl.gtf.gz -p /gpfs/tagc/home/kermezli/project/ologram_plugin_test/Thymus_H3K27ac.bed -c hg19 / ChromInfo.txt -u 1000 -d 1000 -m set -D -if Thymus_H3K27ac_olog.pdf -k 14 `

before having results I had this:  

/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)
/gpfs/tagc/home/kermezli/miniconda2/envs/pygtftk_dev/lib/python3.6/site-packages/pybedtools/bedtool.py:3439: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  return pandas.read_table(self.fn, *args, **kwargs)

**Comment by qferre** [comment]
Sadly, that's not something we can fix. Those warnings are due to pybedtools.
We are debating whether to silence them.

**Comment by dputhier** [comment]
It seems to have been fixed here https://github.com/daler/pybedtools/pull/274

What is your version of pybedtools ?

pip freeze | grep bedtools

**Comment by YasmineKzl** [comment]
version = '0.8.0'

**Comment by dputhier** [comment]
In fact I just checked. It seems that this commit (If I'm not wrong) is not included in the current version of pybedtools (0.8.0). So no way, you will have to wait 0.8.1.

**Comment by YasmineKzl** [comment]
Ok!
Closing.
