### ISSUE TITLE
[ologram] -- issue with chromosomes in ensembl format

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#76]
Not sure but I guess the problem is related to chromosomes viewed as numerics.

      gtftk ologram  -p GRCh38.94_hs_5k_sub.bed -b GRCh38.94_hs_5k_sub.bed -z -V 4 --chrom-info hg38.genome.ens --force-chrom-peak --more-bed-labels bla --force-chrom-more-bed -k 25
[GRCh38.94_hs_5k_sub.bed.txt](https://github.com/dputhier/pygtftk/files/3030056/GRCh38.94_hs_5k_sub.bed.txt)
[hg38.genome.ens.txt](https://github.com/dputhier/pygtftk/files/3030057/hg38.genome.ens.txt)

**Comment by qferre** [comment]
Indeed. It was causing problems, as the pygtftk `chrom_info_as_dict()` function converted them to strings, but the rest of the code did not.

Fixed in ed8ce7f24f552d9c58a8542b3a06de22ed42546d. I have also manually checked the p-values with R :)
