### ISSUE TITLE
Implement strategy for N-fold bed samples comparison

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#80]
If a comma-separated list of bed files is provided as  --peak-file, ologram should run the analysis for each bed then provide a heatmap instead of barplot like I do in the "greatr" package.
I would like to work on this once my PhD manuscript is in good shape if nobody is eager to develop that soon.

**Comment by qferre** [comment]
This would be pretty straightforward. We already provide the tsv file, so it's just a matter of writing the plotnine code based on the file.

Of course, you do not have to read the output file ! The pandas dataframe is accessible in Python code. We can talk about it in person if you are interested in implementing this.

**Comment by dputhier** [comment]
The comma separated is supposed to allow N-fold comparisons. As a workaround, I have implemened merge_ologram_stats that simply take a set of OLOGRAM tsv output file to build a heatmap. Available in 6541a23cd72bc4f30c3b36ba96abd633788f6902

**Comment by qferre** [comment]
I think this is a good plugin, and I think it is also a good idea to separate those two usages, especially since I am developing a multiple-overlap solution that will also use this type of syntax. It could get confusing for the user if we merged the two.

I think this workaround (the merge_ologram_stats) plugin should be the permanent solution, with an explanation in the documentation.

**Comment by qferre** [comment]
I have first draft of a plugin to do an analysis on an entire set of bed files at once (multiple overlaps) and find interesting combinations. We discussed this at length in-person. More detailed explanations will be found in the documentation.

I will push this to the develop branch in the upcoming days. If you've got time to discuss it and/or try it, I would welcome the feedback :)

**Comment by dputhier** [comment]
This is implemented in 1.2.7
