### ISSUE TITLE
[ologram] -- Features whose size is always 1 should not be tested.

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#85]
There is no interest in looking at the distribution of S score when the size of an element is always 1 (e.g SNP, start_codon, stop_codon).
We may indeed set a threshold on feature size.

**Comment by qferre** [comment]
S score (total number of overlapping nucleotides, for those not in the know) will always be computed, so we might as well show it ?

**Comment by dputhier** [comment]
Yes. Indeed...
