### ISSUE TITLE
Add a diagram that display both S and N

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#86]
Any idea ? Maybe a simple scatter plot...

**Comment by qferre** [comment]
I think simple ideas can be the best. A simple scatter plot of the fold change of N vs the fold change of S might be enough. We could plot log(FC) or 1/FC or any other transformation to emphasize small differences.

**Comment by dputhier** [comment]
I added a volcano as suggested by Guillaume. 

As it requires to compute -log10(pval) I have changed the pval == 0  to 1e-320 (just for plotting the diagram). @qferre tell me if its ok to set them to1e-320 . The N and S statistics are treated in the same plot:

![image](https://user-images.githubusercontent.com/1831198/56667766-b9428d80-66ae-11e9-9f6d-cce0aa9ef7d2.png)

Note that the current implementation of ggrepel in plotnine seems to be still in dev so I'm using transparent labels at the moment...

41137fbd349fcf778a1d8cc02a409a9d1c50fadd

**Comment by qferre** [comment]
Putting them at 1e-320 should be okay. I did the same modification for the histograms. Great job :)
Could you add it to the documentation as an example ?

**Comment by dputhier** [comment]
It will be included in the html frame in which the pdf output is enclosed. I was thinking about adding it to the homepage of the doc (?).

**Comment by qferre** [comment]
Sounds like a good idea to me :)
