### ISSUE TITLE
Shuffle Lr and Li across all chromosomes

### ISSUE THREAD

**Issue by qferre** [dputhier/pygtftk#89]
The lists of region lengths and inter region lengths are currently shuffled only within a chromosome. We could implement an option to shuffle this across all chromosomes.

**Comment by qferre** [comment]
I am working on this. A draft will be in the *develop* branch soon.

**Comment by qferre** [comment]
I have a draft for this on the develop branch, in commit 4a6009f6a20f16e45615c4d27dea8fcf43de3c97. It is not used yet : the code is commented and no arguments call for it.

That is because we need to agree on implementation parameters : namely, when shuffling across all chromosomes, should we put the same number of regions on each chromosome ? Follow a Poisson law ? etc.

As a side note, this means we could also do statistics chromosme-by-chromosome.

I would welcome suggestions :)

**Comment by dputhier** [comment]
Closing this at the moment.
