### ISSUE TITLE
[ologram] extension issue

### ISSUE THREAD

**Issue by YasmineKzl** [dputhier/pygtftk#95]
Even I'm sure that my input file is (.gtf.gz), I have this error:  
|-- 20:07-WARNING : Not a valid filename extension :f
 |-- 20:07-ERROR : Extension expected: \.[Gg][Tt][Ff]\.[Gg][Zz]$

The command launched is (on my local machine):
`gtftk  ologram -i tiny_real.gtf.gz -c hg38.genome  -p  ENCFF354QXX_H3K79me2_K562_tiny.bed -u 2000 -d 2000 -D -if ../../../../Desktop/ENCFF354QXX_H3K79me2_K562_tiny.pdf  -j nb_intersections_negbinom_fit_quality `

The weird is that the same command works on sacapus !

**Comment by dputhier** [comment]
Are you using latest develop version ? I think it's related to some trick with argument order. Here it seems that the program captures -i as -if. Try changing argument order. These problems mostly occur when some args may accept 0..n values. If fixed something close to this few commits ago.

**Comment by YasmineKzl** [comment]
Maybe! 
Because when I test without -if argument it's works !
gtftk ologram -i tiny_real.gtf.gz -c hg38.genome -p ENCFF354QXX_H3K79me2_K562_tiny.bed -u 2000 -d 2000 -D -j nb_intersections_negbinom_fit_quality 
Ps: yes, I'm using the latest one!

**Comment by dputhier** [comment]
OK. Go it. We recently changed -if to -pf (--pdf-file-alt) so that all args related to pdf file start with '-p'.
See  #83.
Closing
